### ISSUE TITLE
The max resolution example1 is 720*480

### ISSUE THREAD

**Issue by sankycui** [fyhertz/libstreaming-examples#37]
Hi,
    I found that the max resolution example1 is 720_480,if I changed the resolution was 1080_720 or others,the example APP would crash. 
  My camera  supports 13 million pixels,The log likes:

01-01 12:50:22.865 709-1646/com.baidu.appsearch D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"Built-in Screen", uniqueId "local:0", app 1920 x 1032, real 1920 x 1080, largest app 1920 x 1847, smallest app 1080 x 1007, 60.000004 fps, supportedRefreshRates [60.000004], rotation 0, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 17666666, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
01-01 12:50:23.400 9026-15850/net.majorkernelpanic.example1 I/RtspServer: Connection from 192.168.1.125
01-01 12:50:23.404 9026-15850/net.majorkernelpanic.example1 E/RtspServer: OPTIONS rtsp://192.168.1.154:1234
01-01 12:50:23.404 9026-15850/net.majorkernelpanic.example1 D/RtspServer: RTSP/1.0 200 OK
                                                                          Server: MajorKernelPanic RTSP Server
                                                                          Cseq: 2
                                                                          Content-Length: 0
                                                                          Public: DESCRIBE,SETUP,TEARDOWN,PLAY,PAUSE
01-01 12:50:23.411 9026-15850/net.majorkernelpanic.example1 E/RtspServer: DESCRIBE rtsp://192.168.1.154:1234
01-01 12:50:23.419 174-174/? D/CameraHal: camera_get_camera_info(1337): camera_get_camera_info(1337): camera_0 facing(0), orientation(180)
01-01 12:50:23.436 174-542/? D/CameraHal: camera_get_camera_info(1337): camera_get_camera_info(1337): camera_0 facing(0), orientation(180)
01-01 12:50:23.436 174-542/? W/AudioFlinger: acquireAudioSessionId() unknown client 9026 for session 60
01-01 12:50:23.436 174-542/? I/AwesomePlayer: AwesomePlayer::AwesomePlayer()in
01-01 12:50:23.436 174-542/? I/AwesomePlayer: AwesomePlayer::AwesomePlayer()aftermClient.connect()
01-01 12:50:23.437 174-542/? I/AwesomePlayer: setDataSource_l(<no-scheme URI suppressed>)
01-01 12:50:23.462 174-15857/? I/OMXCodec: --->InstantiateSoftwareCodec create OMX.google.vorbis.decoder codec
01-01 12:50:23.464 174-15857/? I/OMXCodec: Successfully allocated OMX node 'OMX.google.vorbis.decoder'
01-01 12:50:23.465 174-542/? W/AudioFlinger: acquireAudioSessionId() unknown client 9026 for session 61
01-01 12:50:23.465 174-542/? I/AwesomePlayer: AwesomePlayer::AwesomePlayer()in
01-01 12:50:23.465 174-542/? I/AwesomePlayer: AwesomePlayer::AwesomePlayer()aftermClient.connect()
01-01 12:50:23.465 174-542/? I/AwesomePlayer: setDataSource_l(<no-scheme URI suppressed>)
01-01 12:50:23.482 174-15862/? I/OMXCodec: --->InstantiateSoftwareCodec create OMX.google.vorbis.decoder codec
01-01 12:50:23.483 174-15862/? I/OMXCodec: Successfully allocated OMX node 'OMX.google.vorbis.decoder'
01-01 12:50:23.485 174-542/? I/CameraClient: Opening camera 0
01-01 12:50:23.485 174-542/? D/CameraHal: camera_get_camera_info(1337): camera_get_camera_info(1337): camera_0 facing(0), orientation(180)
01-01 12:50:23.485 174-542/? I/CameraHal: camera_device_open(500): camera_device open
01-01 12:50:23.485 174-542/? D/CameraHal: gCameraHalLogLevel: 0
01-01 12:50:23.486 623-5798/com.android.systemui D/mmk: onStatusChangedLocked.+++++++
01-01 12:50:23.486 174-542/? D/CameraHal: CameraHal(133): it is a isp  camera
01-01 12:50:23.486 623-5798/com.android.systemui E/CameraManagerGlobal: Camera id 0 has status changed to 0x80000000
01-01 12:50:23.486 623-5798/com.android.systemui D/mmk: postSingleUpdate.+++++++++ status = -2147483648
01-01 12:50:23.486 623-5798/com.android.systemui D/mmk: postSingleUpdate.+++++++++ status = -2147483648
01-01 12:50:23.486 174-542/? D/CameraHal: Calling process is: net.majorkernelpanic.example1
01-01 12:50:23.486 174-542/? I/vpu_mem_pool: pid 174, open_vpu_memory_pool:473: success
01-01 12:50:23.489 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:717: vpu memory pool size (80000)
01-01 12:50:23.489 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:720: ion_alloc_fd success, memory fd 41
01-01 12:50:23.489 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:717: vpu memory pool size (160000)
01-01 12:50:23.489 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:720: ion_alloc_fd success, memory fd 43
01-01 12:50:23.489 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:717: vpu memory pool size (240000)
01-01 12:50:23.489 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:720: ion_alloc_fd success, memory fd 45
01-01 12:50:23.489 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:717: vpu memory pool size (320000)
01-01 12:50:23.489 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:720: ion_alloc_fd success, memory fd 44
01-01 12:50:23.490 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:717: vpu memory pool size (400000)
01-01 12:50:23.490 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:720: ion_alloc_fd success, memory fd 46
01-01 12:50:23.490 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:717: vpu memory pool size (480000)
01-01 12:50:23.490 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:720: ion_alloc_fd success, memory fd 47
01-01 12:50:23.490 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:717: vpu memory pool size (560000)
01-01 12:50:23.490 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:720: ion_alloc_fd success, memory fd 48
01-01 12:50:23.490 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:717: vpu memory pool size (640000)
01-01 12:50:23.490 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:720: ion_alloc_fd success, memory fd 49
01-01 12:50:23.490 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:717: vpu memory pool size (720000)
01-01 12:50:23.490 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:720: ion_alloc_fd success, memory fd 51
01-01 12:50:23.490 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:717: vpu memory pool size (800000)
01-01 12:50:23.490 174-15869/? I/vpu_mem_pool: pid 174, vpu_mem_allocator:720: ion_alloc_fd success, memory fd 50
01-01 12:50:23.493 174-542/? E/CameraHal: disconnectCamera(1784): getFocusLimits failed!
01-01 12:50:23.579 174-542/? D/CameraHal_Marvin: CameraHal Version Check:
01-01 12:50:23.579 174-542/? D/CameraHal_Marvin:     CamSys_Head.h version: 
                                                        kernel: (0x) v0.b.0
                                                        libisp_siliconimage_isp.so: (0x) v0.b.0
01-01 12:50:23.579 174-542/? D/CameraHal_Marvin:     LibIsp version: 
                                                        local: (0x) v1.27.0
                                                        camera.rk30board.so: (0x) v1.27.0
01-01 12:50:23.579 174-542/? D/CameraHal_Marvin:     Sensor ISI version: 
                                                         libisp_isi_drv_XXX: (0x) v0.a.0
                                                         libisp_siliconimage_isp.so: (0x) v0.a.0
01-01 12:50:23.579 174-542/? D/CameraHal_Marvin:     Tunning XML version:
                                                         libisp_isi_drv_XXX: (22-May-2014_OUYANG_OV13850_FX288_v1.0)
                                                         Calibdb: (06-Aug-2014_ZYL-OYYF_OV13850_CMK-CT0116-FV1_v0.1.2)
01-01 12:50:23.579 174-542/? D/CameraHal_Marvin:     sensor name OV13850: 
                                                        sensor drv version: (0x) v0.9.0
01-01 12:50:23.579 174-542/? E/CameraHal: setupPreview(258): >>>>>>>width_sensor=0,height_sensor=0,preview_w=640,preview_h=480
01-01 12:50:23.579 174-542/? D/CameraHal: setupPreview(306): isp out put format is YUV420SP.
01-01 12:50:23.655 174-542/? E/CameraHal_Marvin: HAL-MOCKUP: PHY ADDR (0x10000000),iommu addr (0x10000000)
01-01 12:50:23.657 174-542/? E/CameraHal_Marvin: HAL-MOCKUP: PHY ADDR (0x112f5000),iommu addr (0x112f5000)
01-01 12:50:23.659 174-542/? E/CameraHal_Marvin: HAL-MOCKUP: PHY ADDR (0x125ea000),iommu addr (0x125ea000)
01-01 12:50:23.661 174-542/? E/CameraHal_Marvin: HAL-MOCKUP: PHY ADDR (0x138df000),iommu addr (0x138df000)
01-01 12:50:23.726 174-542/? E/CameraHal: cameraCreate(137): sensor name OV13850
01-01 12:50:23.728 174-542/? D/CameraHal: initDefaultParameters(981): ------mHardInfo.mVcmInfo.mVcmDrvName in not NC-----
01-01 12:50:23.729 174-542/? D/CameraHal: enableSensor(213): orientation = 0xb7adbaf0 (MPL accel)
01-01 12:50:23.730 463-915/system_process V/Sensors: int poll__setDelay(sensors_poll_device_t_, int, int64_t)
01-01 12:50:23.730 463-915/system_process V/Sensors: int sensors_poll_context_t::setDelay(int, int64_t)
01-01 12:50:23.730 463-915/system_process V/Sensors: setDelay - sensor Accelerometer (handle 4), rate 20 ms (50.00 Hz)
01-01 12:50:23.730 463-915/system_process E/Sensors: MPU is not available
01-01 12:50:23.731 463-943/system_process V/Sensors: int poll__setDelay(sensors_poll_device_t_, int, int64_t)
01-01 12:50:23.731 463-943/system_process V/Sensors: int sensors_poll_context_t::setDelay(int, int64_t)
01-01 12:50:23.731 463-943/system_process V/Sensors: setDelay - sensor Accelerometer (handle 4), rate 66 ms (15.00 Hz)
01-01 12:50:23.731 463-943/system_process E/Sensors: MPU is not available
01-01 12:50:23.731 174-542/? W/CameraService: CameraService::connect X (id 0, this pid is 174, name net.majorkernelpanic.example1)
01-01 12:50:23.735 9026-15850/net.majorkernelpanic.example1 V/VideoQuality: Supported resolutions: 176x144, 320x240, 352x288, 640x480, 720x480, 800x600, 4224x3136, 4224x3136, 1280x720, 1920x1080, 2112x1568, 2112x1568, 2112x1568, 2112x1568, 2112x1568, 2064x1548
01-01 12:50:23.735 9026-15850/net.majorkernelpanic.example1 V/VideoQuality: Supported frame rates: 3-30fps
01-01 12:50:23.737 174-15880/? D/CameraHal: commandThread(937): commandThread(937):receive CMD_SET_PREVIEW_WINDOW
01-01 12:50:23.737 174-15880/? D/CameraHal: commandThread(953): commandThread(953): CMD_SET_PREVIEW_WINDOW out
01-01 12:50:23.738 174-15880/? D/CameraHal: commandThread(832): commandThread(832):receive CMD_PREVIEW_START
01-01 12:50:23.738 174-15880/? D/CameraHal: stop(1859): m_camDevice->stopPreview success!
01-01 12:50:23.739 174-15880/? E/CameraHal_Marvin: OV13850:  STREAM OFF ++++++++++++++
01-01 12:50:23.741 174-15880/? E/CameraHal_Marvin: OV13850:  STREAM OFF ++++++++++++++
01-01 12:50:23.742 174-15880/? E/CameraHal: setupPreview(258): >>>>>>>width_sensor=2112,height_sensor=1568,preview_w=2112,preview_h=1568
01-01 12:50:23.742 174-15880/? D/CameraHal: setupPreview(306): isp out put format is YUV420SP.
01-01 12:50:23.744 174-15880/? D/CameraHal: start(1814): m_camDevice->startPreview success
01-01 12:50:23.744 174-15868/? D/CameraHal: displayThread(596): displayThread(596): receive CMD_DISPLAY_START
01-01 12:50:23.744 174-15868/? D/CameraHal: cameraDisplayBufferDestory(399): cameraDisplayBufferDestory(399): mANativeWindow is NULL, destory is ignore
01-01 12:50:23.745 168-255/? W/gralloc:  Debugmem The fd=32, in vmalloc !!!! Ishwc=0
01-01 12:50:23.746 168-447/? W/gralloc:  Debugmem The fd=89, in vmalloc !!!! Ishwc=0
01-01 12:50:23.747 168-251/? W/gralloc:  Debugmem The fd=92, in vmalloc !!!! Ishwc=0
01-01 12:50:23.748 168-952/? W/gralloc:  Debugmem The fd=94, in vmalloc !!!! Ishwc=0
01-01 12:50:23.749 174-15880/? D/CameraHal: commandThread(905): commandThread(905): CMD_PREVIEW_START out
01-01 12:50:23.805 9026-15886/net.majorkernelpanic.example1 I/OMXClient: Using client-side OMX mux.
01-01 12:50:23.811 9026-15886/net.majorkernelpanic.example1 I/ACodec: setupVideoEncoder succeeded
01-01 12:50:23.815 174-15887/? E/ROCKCHIP_VIDEO_ENC: EncParam.framerate  = 20 outPort->sPortParam.format.video.xFramerate = 1310720 1000000
01-01 12:50:23.815 174-15887/? E/ROCKCHIP_VIDEO_ENC: ConvertOmxAvcLevelToAvcSpecLevel: 512
01-01 12:50:23.815 174-15887/? D/pv_avcenc_api: cml->cabacintIdc  0 cml->enablaCabac 0 cml->intraPicRate 20
01-01 12:50:23.815 174-15887/? D/pv_avcenc_api: init intraPeriodCnt 20
01-01 12:50:25.399 9026-15919/net.majorkernelpanic.example1 I/OMXClient: Using client-side OMX mux.
01-01 12:50:25.419 174-1000/? E/ROCKCHIP_VIDEO_DECCONTROL: OMX_IndexParamdescribeColorFormat get 
01-01 12:50:25.420 174-1000/? E/ROCKCHIP_OSAL_Android: OMX_ERRORTYPE Rockchip_OSAL_GetANBParameter(OMX_HANDLETYPE, OMX_INDEXTYPE, OMX_PTR): Rockchip_OMX_Check_SizeVersion(DescribeColorFormatParams) is failed
01-01 12:50:25.420 174-1000/? E/OMXNodeInstance: getParameter(25c:rk._decoder.avc, ??(0x7f000017)) ERROR: BadParameter(0x80001005)
01-01 12:50:25.421 174-542/? E/ROCKCHIP_VIDEO_DECCONTROL: OMX_IndexParamdescribeColorFormat get 
01-01 12:50:25.422 174-174/? E/ROCKCHIP_OSAL_Android: OMX_ERRORTYPE Rockchip_OSAL_GetANBParameter(OMX_HANDLETYPE, OMX_INDEXTYPE, OMX_PTR): Rockchip_OMX_Check_SizeVersion(DescribeColorFormatParams) is failed
01-01 12:50:25.422 174-174/? E/OMXNodeInstance: getParameter(25c:rk._decoder.avc, ??(0x7f000017)) ERROR: BadParameter(0x80001005)
01-01 12:50:25.428 174-1000/? E/ROCKCHIP_VIDEO_DECCONTROL: OMX_IndexParamdescribeColorFormat get 
01-01 12:50:25.429 174-999/? E/ROCKCHIP_OSAL_Android: OMX_ERRORTYPE Rockchip_OSAL_GetANBParameter(OMX_HANDLETYPE, OMX_INDEXTYPE, OMX_PTR): Rockchip_OMX_Check_SizeVersion(DescribeColorFormatParams) is failed
01-01 12:50:25.429 174-999/? E/OMXNodeInstance: getParameter(25c:rk._decoder.avc, ??(0x7f000017)) ERROR: BadParameter(0x80001005)
01-01 12:50:25.430 174-507/? E/OMXNodeInstance: getConfig(25c:rk._decoder.avc, ConfigCommonOutputCrop(0x700000f)) ERROR: UnsupportedIndex(0x8000101a)
01-01 12:50:25.457 174-15923/? I/H264_DEBUG: init done status 0, ts_en = 0 debug 0
01-01 12:50:25.513 174-15924/? I/H264_DEBUG: decoded width 1920  decoded height 1088
01-01 12:50:25.513 174-15924/? I/H264_DEBUG: display width 1920, display height 1080
01-01 12:50:25.573 174-507/? E/ROCKCHIP_VIDEO_DECCONTROL: OMX_IndexParamdescribeColorFormat get 
01-01 12:50:25.573 174-999/? E/ROCKCHIP_OSAL_Android: OMX_ERRORTYPE Rockchip_OSAL_GetANBParameter(OMX_HANDLETYPE, OMX_INDEXTYPE, OMX_PTR): Rockchip_OMX_Check_SizeVersion(DescribeColorFormatParams) is failed
01-01 12:50:25.573 174-999/? E/OMXNodeInstance: getParameter(25c:rk._decoder.avc, ??(0x7f000017)) ERROR: BadParameter(0x80001005)
01-01 12:50:25.574 174-508/? E/OMXNodeInstance: getConfig(25c:rk._decoder.avc, ConfigCommonOutputCrop(0x700000f)) ERROR: UnsupportedIndex(0x8000101a)
01-01 12:50:27.530 174-15920/? I/H264_DEBUG: deinit DONE
01-01 12:50:27.782 9026-15962/net.majorkernelpanic.example1 I/RtspServer: Connection from 192.168.1.125
01-01 12:50:27.783 9026-15962/net.majorkernelpanic.example1 E/RtspServer: OPTIONS rtsp://192.168.1.154:1234
01-01 12:50:27.783 9026-15962/net.majorkernelpanic.example1 D/RtspServer: RTSP/1.0 200 OK
                                                                          Server: MajorKernelPanic RTSP Server
                                                                          Cseq: 1
                                                                          Content-Length: 0
                                                                          Public: DESCRIBE,SETUP,TEARDOWN,PLAY,PAUSE
01-01 12:50:27.788 9026-15962/net.majorkernelpanic.example1 I/RtspServer: Client disconnected
01-01 12:50:28.191 9026-15850/net.majorkernelpanic.example1 W/System.err: java.lang.RuntimeException: Incorrect U or V pane...
01-01 12:50:28.191 9026-15850/net.majorkernelpanic.example1 W/System.err:     at net.majorkernelpanic.streaming.hw.EncoderDebugger.debug(EncoderDebugger.java:289)
01-01 12:50:28.191 9026-15850/net.majorkernelpanic.example1 W/System.err:     at net.majorkernelpanic.streaming.hw.EncoderDebugger.debug(EncoderDebugger.java:116)
01-01 12:50:28.191 9026-15850/net.majorkernelpanic.example1 W/System.err:     at net.majorkernelpanic.streaming.video.H264Stream.testMediaCodecAPI(H264Stream.java:133)
01-01 12:50:28.191 9026-15850/net.majorkernelpanic.example1 W/System.err:     at net.majorkernelpanic.streaming.video.H264Stream.testH264(H264Stream.java:119)
01-01 12:50:28.191 9026-15850/net.majorkernelpanic.example1 W/System.err:     at net.majorkernelpanic.streaming.video.H264Stream.configure(H264Stream.java:111)
01-01 12:50:28.191 9026-15850/net.majorkernelpanic.example1 W/System.err:     at net.majorkernelpanic.streaming.Session.syncConfigure(Session.java:395)
01-01 12:50:28.191 9026-15850/net.majorkernelpanic.example1 W/System.err:     at net.majorkernelpanic.streaming.rtsp.RtspServer$WorkerThread.processRequest(RtspServer.java:439)
01-01 12:50:28.191 9026-15850/net.majorkernelpanic.example1 W/System.err:     at net.majorkernelpanic.streaming.rtsp.RtspServer$WorkerThread.run(RtspServer.java:390)
01-01 12:50:28.275 9026-15968/net.majorkernelpanic.example1 I/OMXClient: Using client-side OMX mux.
01-01 12:50:28.280 9026-15968/net.majorkernelpanic.example1 I/ACodec: setupVideoEncoder succeeded
01-01 12:50:28.282 174-15969/? E/ROCKCHIP_VIDEO_ENC: EncParam.framerate  = 20 outPort->sPortParam.format.video.xFramerate = 1310720 1000000
01-01 12:50:28.282 174-15969/? E/ROCKCHIP_VIDEO_ENC: ConvertOmxAvcLevelToAvcSpecLevel: 512
01-01 12:50:28.282 174-15969/? D/pv_avcenc_api: cml->cabacintIdc  0 cml->enablaCabac 0 cml->intraPicRate 20
01-01 12:50:28.283 174-15969/? D/pv_avcenc_api: init intraPeriodCnt 20
01-01 12:50:28.939 709-1646/com.baidu.appsearch D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"Built-in Screen", uniqueId "local:0", app 1920 x 1032, real 1920 x 1080, largest app 1920 x 1847, smallest app 1080 x 1007, 60.000004 fps, supportedRefreshRates [60.000004], rotation 0, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 17666666, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
01-01 12:50:29.805 9026-15998/net.majorkernelpanic.example1 I/OMXClient: Using client-side OMX mux.
01-01 12:50:29.811 174-508/? E/ROCKCHIP_VIDEO_DECCONTROL: OMX_IndexParamdescribeColorFormat get 
01-01 12:50:29.811 174-1000/? E/ROCKCHIP_OSAL_Android: OMX_ERRORTYPE Rockchip_OSAL_GetANBParameter(OMX_HANDLETYPE, OMX_INDEXTYPE, OMX_PTR): Rockchip_OMX_Check_SizeVersion(DescribeColorFormatParams) is failed
01-01 12:50:29.811 174-1000/? E/OMXNodeInstance: getParameter(25e:rk._decoder.avc, ??(0x7f000017)) ERROR: BadParameter(0x80001005)
01-01 12:50:29.812 174-999/? E/ROCKCHIP_VIDEO_DECCONTROL: OMX_IndexParamdescribeColorFormat get 
01-01 12:50:29.812 174-507/? E/ROCKCHIP_OSAL_Android: OMX_ERRORTYPE Rockchip_OSAL_GetANBParameter(OMX_HANDLETYPE, OMX_INDEXTYPE, OMX_PTR): Rockchip_OMX_Check_SizeVersion(DescribeColorFormatParams) is failed
01-01 12:50:29.812 174-507/? E/OMXNodeInstance: getParameter(25e:rk._decoder.avc, ??(0x7f000017)) ERROR: BadParameter(0x80001005)
01-01 12:50:29.816 174-1000/? E/ROCKCHIP_VIDEO_DECCONTROL: OMX_IndexParamdescribeColorFormat get 
01-01 12:50:29.816 174-174/? E/ROCKCHIP_OSAL_Android: OMX_ERRORTYPE Rockchip_OSAL_GetANBParameter(OMX_HANDLETYPE, OMX_INDEXTYPE, OMX_PTR): Rockchip_OMX_Check_SizeVersion(DescribeColorFormatParams) is failed
01-01 12:50:29.816 174-174/? E/OMXNodeInstance: getParameter(25e:rk._decoder.avc, ??(0x7f000017)) ERROR: BadParameter(0x80001005)
01-01 12:50:29.817 174-999/? E/OMXNodeInstance: getConfig(25e:rk._decoder.avc, ConfigCommonOutputCrop(0x700000f)) ERROR: UnsupportedIndex(0x8000101a)
01-01 12:50:29.832 174-16002/? I/H264_DEBUG: init done status 0, ts_en = 0 debug 0
01-01 12:50:29.890 174-16003/? I/H264_DEBUG: decoded width 1920  decoded height 1088
01-01 12:50:29.890 174-16003/? I/H264_DEBUG: display width 1920, display height 1080
01-01 12:50:29.932 174-174/? E/ROCKCHIP_VIDEO_DECCONTROL: OMX_IndexParamdescribeColorFormat get 
01-01 12:50:29.933 174-507/? E/ROCKCHIP_OSAL_Android: OMX_ERRORTYPE Rockchip_OSAL_GetANBParameter(OMX_HANDLETYPE, OMX_INDEXTYPE, OMX_PTR): Rockchip_OMX_Check_SizeVersion(DescribeColorFormatParams) is failed
01-01 12:50:29.933 174-507/? E/OMXNodeInstance: getParameter(25e:rk._decoder.avc, ??(0x7f000017)) ERROR: BadParameter(0x80001005)
01-01 12:50:29.933 174-507/? E/OMXNodeInstance: getConfig(25e:rk._decoder.avc, ConfigCommonOutputCrop(0x700000f)) ERROR: UnsupportedIndex(0x8000101a)
01-01 12:50:31.873 174-15999/? I/H264_DEBUG: deinit DONE

**Comment by j796160836** [comment]
HI, what is your bitrate use for 720x480 ?
I tried 640x480 at Samsung S7 and Nexus 5 but failed.
I use Example 1 for custom url, which is describe in [UriParser.java](https://github.com/fyhertz/libstreaming/blob/aff43927e63f2fcbf50e4f896d40b58301644cb7/src/net/majorkernelpanic/streaming/rtsp/UriParser.java)

URL:
rtsp://192.168.1.154:1234/?h264=500-30-320-240
It means **500kbps, 30fps, 320x240**.

I have tried

| URLs | Result |
| --- | --- |
| rtsp://192.168.1.154:1234/?h264=500-30-320-240 | passed |
| rtsp://192.168.201.6:1234/?h264=7500-30-320-240 | passed |
| rtsp://192.168.201.6:1234/?h264=7500-30-1280-720 | failed |
| rtsp://192.168.201.6:1234/?h264=7500-30-640-480 | failed |

**Comment by LuuHieu** [comment]
I can not stream with resolution greater than 320x240. Have you solved the issue

**Comment by j796160836** [comment]
@LuuHieu No too.

**Comment by teamclouday** [comment]
For anyone who cannot use high resolution for rtsp server, [here](https://stackoverflow.com/questions/49407803/libstreaming-gives-black-screen-when-change-resolution) is a solution.  

What I did is to change libstreaming/video/H264Stream.java, `testMediaCodecAPI()` function  
from:  
```java
if (mQuality.resX>=640) {
	// Using the MediaCodec API with the buffer method for high resolutions is too slow
	mMode = MODE_MEDIARECORDER_API;
}
```

to:  
```java
if (mQuality.resY>1080) {
	// Using the MediaCodec API with the buffer method for high resolutions is too slow
	mMode = MODE_MEDIARECORDER_API;
}
```

Now start rtsp server and connect to `rtsp://xxx.xxx.xxx.xxx:port?h264=50000-30-1280-720` will work.
