### ISSUE TITLE
CameraInUseException

### ISSUE THREAD

**Issue by mbpz** [fyhertz/libstreaming-examples#44]
01-11 15:38:09.994 4123-4231/ E/RtspServer: DESCRIBE rtsp://192.168.1.248:1234
01-11 15:38:10.046 4123-4233/ W/CameraBase: An error occurred while connecting to camera: 0
01-11 15:38:10.046 4123-4231/ E/RtspServer: Fail to connect to camera service
01-11 15:38:10.046 4123-4231/ W/System.err: net.majorkernelpanic.streaming.exceptions.CameraInUseException: Fail to connect to camera service
01-11 15:38:10.046 4123-4231/ W/System.err:     at net.majorkernelpanic.streaming.video.VideoStream.openCamera(VideoStream.java:565)
01-11 15:38:10.046 4123-4231/ W/System.err:     at net.majorkernelpanic.streaming.video.VideoStream.createCamera(VideoStream.java:575)
01-11 15:38:10.046 4123-4231/ W/System.err:     at net.majorkernelpanic.streaming.video.H264Stream.testMediaCodecAPI(H264Stream.java:125)
01-11 15:38:10.047 4123-4231/ W/System.err:     at net.majorkernelpanic.streaming.video.H264Stream.testH264(H264Stream.java:119)
01-11 15:38:10.047 4123-4231/ W/System.err:     at net.majorkernelpanic.streaming.video.H264Stream.configure(H264Stream.java:111)
01-11 15:38:10.047 4123-4231/ W/System.err:     at net.majorkernelpanic.streaming.Session.syncConfigure(Session.java:395)
01-11 15:38:10.047 4123-4231/ W/System.err:     at net.majorkernelpanic.streaming.rtsp.RtspServer$WorkerThread.processRequest(RtspServer.java:463)
01-11 15:38:10.047 4123-4231/ W/System.err:     at net.majorkernelpanic.streaming.rtsp.RtspServer$WorkerThread.run(RtspServer.java:406)
01-11 15:38:10.047 4123-4231/ D/RtspServer: RTSP/1.0 500 Internal Server Error
                                                               Server: MajorKernelPanic RTSP Server
                                                               Cseq: 3
                                                               Content-Length: 0

**Comment by mbpz** [comment]
RTSP/1.0 500 Internal Server Error
